pip install trl
pip install bitsandbytes
pip install transformers
pip install datasets
pip install deepspeed
pip install torch
pip install networkx
pip install numpy
pip install matplotlib
pip install tqdm